name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Configure NPM
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.RELEASE_TOKEN }}
          npm config set @ollyrowe:registry https://npm.pkg.github.com

      - name: Install dependencies
        run: yarn
      - name: Install semantic-release extra plugins
        run: yarn add --dev @semantic-release/changelog @semantic-release/git

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: npx semantic-release
